version: "2"
x-redash-service: &redash-service
  #现在image的值为中文开源版的tag如果要使用官方的镜像，在docker hub上查看官方tag，然后替换。
  image: dazdata/redash:v10-21.11.19
  depends_on:
    - postgres
    - redis
  environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: INFO
      REDASH_REDIS_URL: redis://redis:6379/0
      POSTGRES_PASSWORD: aaa123456
      REDASH_COOKIE_SECRET: wo3urion23i4un2l34jm2l34k
      REDASH_SECRET_KEY: u2o34nlfksjelruirk
      REDASH_DATABASE_URL: "postgresql://postgres:aaa123456@postgres/postgres"
      ORACLE_HOME: "/usr/lib/oracle/12.2/client64"
      LD_LIBRARY_PATH: "/usr/lib/oracle/12.2/client64/lib"
      REDASH_FEATURE_ALLOW_CUSTOM_JS_VISUALIZATIONS: "true"
      REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.oracle,redash.query_runner.python"
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
  worker:
    <<: *redash-service
    command: worker
    environment:
      WORKERS_COUNT: 4
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:12-alpine
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: dazdata/redash-nginx:latest
    ports:
      - "5000:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
